# Generated by Django 2.2.10 on 2021-10-20 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20211020_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quuiz', to='polls.Quiz'),
        ),
    ]
